In [2]:
# Module pour manipulation et traitement des données
import pandas as pd
import numpy as np
# Module pour lecture Json
import json
# Module pour requeter API
import requests
from pprint import pprint
from tqdm import tqdm

In [3]:
# Chargement du fichier CSV
df_tt = pd.read_csv("id pour API 07.05.26.csv", sep=",")

In [4]:
# Voir les colonnes du dataframe
print(df_tt.columns)

Index(['Unnamed: 0', 'id_tmdb', 'imdb_id'], dtype='str')

In [5]:
# Création de la liste des IDs IMDb
list_id_tmdb = df_tt["imdb_id"].dropna().unique()

In [6]:
# Liste vide pour stocker les résultats
liste_data_temp = []

In [7]:
df_tt.head()

   Unnamed: 0  id_tmdb     imdb_id
0           0  1048595  tt10300344
1           1      109   tt0111507
2           2      194   tt0211915
3           3      300   tt0354899
4           4      892   tt0101700

In [8]:
# Liste vide pour stocker les réponses JSON
liste_vide = []

# Boucle sur chaque ID de film TMDB
for movies_id in tqdm(df_tt["id_tmdb"]):

    # URL pour récupérer les vidéos du film
    url = f"https://api.themoviedb.org/3/movie/{movies_id}/videos?language=fr-FR"

    # Headers avec ton token
    headers = {
        "accept": "application/json",
       "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5Y2IwZTY2ZDU4M2NlMjRlNzhkMWIyNzc2YmUxYTJiMCIsIm5iZiI6MTc3NzI5NjYzNS4wODksInN1YiI6IjY5ZWY2NGZiYTQ5YzYxY2QwNzE1MWFiNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.kcNXcdjcIvWsz84XKCFBrOopCYfR7g4yg-IMIV2YYbU"
    }

    # Requête API
    response = requests.get(url, headers=headers)

    # Transformation de la réponse en JSON
    data_json = response.json()

    # Ajouter l'id du film dans le JSON
    data_json["movie_id"] = movies_id

    # Ajouter le JSON dans la liste
    liste_vide.append(data_json)

100%|██████████| 1558/1558 [10:00<00:00,  2.60it/s]

In [9]:
liste_film = []
for film in liste_vide:
  df = pd.json_normalize(film['results'])
  liste_film.append(df)

In [10]:
# Fusionner tous les dataframes
df_videos = pd.concat(liste_film, ignore_index=True)

In [14]:
# Garder uniquement les vidéos YouTube
df_videos = df_videos[
    df_videos["site"] == "YouTube"
]

In [15]:
# Garder uniquement les Trailer et Teaser
df_videos = df_videos[
    df_videos["type"].isin(["Trailer", "Teaser"])
]

In [16]:
# Créer l'URL YouTube complète
df_videos["youtube_url"] = (
    "https://www.youtube.com/watch?v=" + df_videos["key"]
)

In [17]:
df_videos[
    ["name", "type", "site", "key", "youtube_url"]
].head()

,name,type,site,key,youtube_url
0,Trailer Trois Couleurs: Blanc,Trailer,YouTube,uBEku1kG1fo,https://www.youtube.com/watch?v=uBEku1kG1fo
1,Bande annonce Le fabuleux destin d'Amélie Poulain,Trailer,YouTube,_cZyjM_R6-E,https://www.youtube.com/watch?v=_cZyjM_R6-E
3,La science des rêves - Bande annonce,Trailer,YouTube,koacpw5a8Ro,https://www.youtube.com/watch?v=koacpw5a8Ro
4,Delicatessen (Bande annonce Vf),Trailer,YouTube,aWEUHqGX_T0,https://www.youtube.com/watch?v=aWEUHqGX_T0
7,TOUJOURS POSSIBLE Bande Annonce (2025) Amanda ...,Trailer,YouTube,LEJU-puemyM,https://www.youtube.com/watch?v=LEJU-puemyM

In [19]:
# Export CSV final
df_videos.to_csv("API MOVIES VIDEOS.csv", index=False)